import { useRouter } from "next/router";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Signin.module.css'
import { useState } from "react";
import axios from 'axios'

export default function Signin() {
    const [loginType,setLoginType]=useState('login')

    const [firstName,setFirstName]=useState('')
    const [lastName,setLastName]=useState('')
    const [email,setEmail]=useState('')
    const [password,setPassword]=useState('')
    const [passwordCheck,setPasswordCheck]=useState('')

    const toggle = (param) => {
        setLoginType(param)
        setFirstName('')
        setLastName('')
        setEmail('')
        setPassword('')
        setPasswordCheck('')
    }
    const handleSubmit = (e,type) => {
        e.preventDefault();
        console.log(e,'sjfle',email,password)
        switch (type) {
            case 'login':
                axios.post('/auth/login',{
                    email,password
                }).then((res)=>{console.log('login success',res)}).catch((err)=>{console.log('login failed',err?.response)})
                break;
            case 'signup':
                axios.post('/auth/signup',{
                    firstName,lastName,email,password
                }).then((res)=>{console.log('signup success',res)}).catch((err)=>{console.log('signup failed',err?.response)})
                break;
            case 'forgot-password':
              axios.put('/auth/forgot-password',{email}).then((res)=>{console.log('forgot-password accepted',res)}).catch((err)=>{console.log('forgot-password failed',err?.response)})
              break;
            default:
              break;
        }
        setFirstName('')
        setLastName('')
        setEmail('')
        setPassword('')
        setPasswordCheck('')

    }
    return (<div>
        <Head>
      <title>HospitalFinder - Sign in -</title>
      <meta name="description" content="Generated by cna" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
    <div className={styles.body}>
    <div className={`${styles.fullScreenContainer} ${loginType==='login'?'':styles.rotateY180}`}>
      <div className={styles.loginContainer}>
        <h3 className={styles.loginTitle}>Welcome</h3>
        <form onSubmit={(e)=>handleSubmit(e,'login')}>
          <div className={styles.inputGroup}>
            <label>Email</label>
            <input type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/>
          </div>
          <div className={styles.inputGroup}>
            <label>Password</label>
            <input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} />
          </div><div style={{display:'flex', flexDirection:'row'}}>
          <button type="submit" className={styles.loginButton}>Log In</button>
          <button type="button" className={styles.loginButton} onClick={()=>toggle('forgot-password')}>Forget Password?</button>
          </div>
        </form>
        <button className={styles.loginButton} onClick={()=>toggle('signup')}>Or Create a new Account</button>
      </div>
      <div className={styles.signupContainer}>
        <h3 className={styles.loginTitle}>Welcome</h3>
        {loginType==='signup'?
        <form onSubmit={(e)=>handleSubmit(e,'signup')}>
        <div className={styles.inputGroup}>
            <label>First Name</label>
            <input type="text" value={firstName} onChange={(e)=>setFirstName(e.target.value)}/>
          </div>
          <div className={styles.inputGroup}>
            <label>Last Name</label>
            <input type="text" value={lastName} onChange={(e)=>setLastName(e.target.value)}/>
          </div>
          <div className={styles.inputGroup}>
            <label>Email</label>
            <input type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/>
          </div>
          <div className={styles.inputGroup}>
            <label>Password</label>
            <input type="password" value={password} onChange={(e)=>setPassword(e.target.value)}/>
          </div>
          <div className={styles.inputGroup}>
            <label>Check Password</label>
            <input type="password" value={passwordCheck} onChange={(e)=>setPasswordCheck(e.target.value)}/>
          </div>
          <button type="submit" className={styles.loginButton}>Sign Up</button>
        </form>
        :
        <form onSubmit={(e)=>handleSubmit(e,'forgot-password')}>
          <div className={styles.inputGroup}>
            <label>Email</label>
            <input type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/>
          </div>
          <button type="submit" className={styles.loginButton}>Reset Password</button>
        </form>
        }
        <button className={styles.loginButton} onClick={()=>toggle('login')}>Or Log in</button>
      </div>
    </div>
  </div>
    </main>
    </div>)
}
