import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Signin.module.css";
import { useState } from "react";
import axios from "axios";

export default function ResetPasswordSignin() {
  const [password, setPassword] = useState("");
  const [passwordCheck, setPasswordCheck] = useState("");
  const Router = useRouter();

  const toggle = (param) => {
    setEmail("");
    setPassword("");
    setPasswordCheck("");
  };
  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(e, "sjfle", Router.query.token, password);

    axios
      .put(`/auth/reset-password/${Router.query.token}`, {
        newPassword: password,
      })
      .then((res) => {
        console.log("login success", res);
      })
      .catch((err) => {
        console.log("login failed", err?.response);
      });

    setPassword("");
    setPasswordCheck("");
  };
  return (
    <div>
      <Head>
        <title>HospitalFinder - reset password -</title>
        <meta name="description" content="Generated by cna" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.body}>
          <div className={`${styles.fullScreenContainer}`}>
            <div className={styles.loginContainer}>
              <h3 className={styles.loginTitle}>Reset You Password</h3>
              <form onSubmit={(e) => handleSubmit(e)}>
                <div className={styles.inputGroup}>
                  <label>New Password</label>
                  <input
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </div>
                <div className={styles.inputGroup}>
                  <label>New Password again</label>
                  <input
                    type="password"
                    value={password}
                    onChange={(e) => setCheckPassword(e.target.value)}
                  />
                </div>
                <button type="submit" className={styles.loginButton}>
                  Log In
                </button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
