import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Router from 'next/router'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { validToken } from '../reducers/token'
import { updateUserData } from '../reducers/user'
import styles from '../styles/Home.module.css'

export default function Home() {
  const state = useSelector((state) => {
    return{ user: state.user.userData, token:state.token.loginToken };
  });
  const dispatch = useDispatch()
  useEffect(()=>{
    axios.get('/user',{
      headers:{ Authorization: `Bearer ${document.cookie.split('; ').find(e=>e.startsWith('hospitalsToken='))?.split('=')[1]}`}
    })
    .then(res=>{
      console.log('response',res.data); 
      dispatch(validToken())
      dispatch(updateUserData(res.data))
      Router.push('/home')
    })
    .catch(err=>{
      Router.push('/signin')
      console.log('catch err',err.response,'lll',localStorage?.getItem('hospitalsToken'));
    })
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>CNA</title>
        <meta name="description" content="Generated by cna" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
 

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
